### ISSUE TITLE
Some Problem

### ISSUE THREAD

**Issue by PoplarYang** [rodrigoluissilva/Zabbix-JMX-Tomcat-Extended-Template#1]
Sorry to intrrupt you.
The problem is follow:
I use "Template JMX Generic - Extended", but "Template JMX Generic - Extended: MemoryPool - PS Perm Gen used" shows that status is Not supported.

I also see "Zabbix JMX Tomcat Extended Template
configure Macros
{$AJP_PORT}
{$CONNECTOR_MODE}
{$HTTPS_PORT}
{$HTTP_PORT}", but I don't know how to config it.

So,I need your help.Thank you!
You can mail me echohiyang@foxmail.com.

**Comment by rodrigoluissilva** [comment]
Hi there,

First of all you have to **configure your Zabbix Java Gateway**
https://www.zabbix.com/documentation/2.0/manual/concepts/java#configuring_server_for_use_with_java_gateway

Second, you have to **enable the JMX Remote** on your java
Something like
https://www.zabbix.com/documentation/2.4/manual/config/items/itemtypes/jmx_monitoring

`-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=12345 -Dcom.sun.management.jmxremote.rmi.port=12345`

on your startup script

**Macros**
Look in your logs for these lines

```
INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-apr-8080"]
INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-apr-8009"]
```

and fill the macros

{$AJP_PORT} = 8009
{$CONNECTOR_MODE} = apr
{$HTTPS_PORT} = 
{$HTTP_PORT} = 8080

If everything is OK you'll see some information being collected 
Some items are not supported by all java implementation, use jconsole to see all items
http://docs.oracle.com/javase/1.5.0/docs/guide/management/agent.html

**Comment by PoplarYang** [comment]
Thanks
